//
//  InitInformation.swift
//  CourseWork
//
//  Created by Andrew Landiak on 12.05.2022.
//

import Foundation
import SwiftUI

class InitInformation: ObservableObject {
    @ObservedObject var learningVM = LearningListViewModel()
    func addInformationCoreData() {
        let animal = LearningViewModel(id: UUID(), name: "Zebra", origin: "Africa", info: "Zebras are African equines with distinctive black-and-white striped coats. There are three living species: the Grévy's zebra, plains zebra, and the mountain zebra. Zebras share the genus Equus with horses and asses, the three groups being the only living members of the family Equidae. Zebra stripes come in different patterns, unique to each individual.  Zebras inhabit eastern and southern Africa and can be found in a variety of habitats such as savannahs, grasslands, woodlands, shrublands, and mountainous areas.Zebras are primarily grazers and can subsist on lower-quality vegetation. They are preyed on mainly by lions and typically flee when threatened but also bite and kick.Zebras communicate with various vocalisations, body postures and facial expressions. Social grooming strengthens social bonds in plains and mountain zebras.Zebras' dazzling stripes make them among the most recognisable mammals. They have been featured in art and stories in Africa and beyond. Historically, they have been highly sought after by exotic animal collectors, but unlike horses and donkeys, zebras have never been truly domesticated.", youtube: "https://www.youtube.com/watch?v=kWxnadQI5Qw", size: "2.7 methers", classtype: "Mammal", age: "20-30", weight: 350)
        
        let animal_02 = LearningViewModel(id: UUID(), name: "Deer", origin: "Eurasia", info: "Deer or true deer are hoofed ruminant mammals forming the family Cervidae. The two main groups of deer are the Cervinae, including the muntjac, the elk, the red deer, and the fallow deer; and the Capreolinae, including the reindeer, white-tailed deer, the roe deer, and the moose. Male deer of all species as well as female reindeer, grow and shed new antlers each year.  The musk deer of Asia and chevrotains of tropical African and Asian forests are separate families that are also in the ruminant clade Ruminantia; they are not especially closely related to Cervidae. Deer appear in art from Paleolithic cave paintings onwards, and they have played a role in mythology, religion, and literature throughout history, as well as in heraldry, such as red deer that appear in the coat of arms of Åland.Their economic importance includes the use of their meat as venison, their skins as soft, strong buckskin, and their antlers as handles for knives. Deer hunting has been a popular activity since the Middle Ages and remains a resource for many families today.", youtube: "https://www.youtube.com/watch?v=cAR90Z0b-rA", size: "4.7 methers", classtype: "Mammal", age: "6-10", weight: 1400)
        
        let animal_03 = LearningViewModel(id: UUID(), name: "Elk", origin: "North America", info: "The elk is one of the largest species within the deer family and one of the largest terrestrial mammals in its native range of North America, as well as Central and East Asia.  Elk range in forest and forest-edge habitat, feeding on grasses, plants, leaves, and bark. Male elk have large antlers which they shed each year. Males also engage in ritualized mating behaviors during the rut, including posturing, antler wrestling and bugling, a loud series of vocalizations that establishes dominance over other males and attracts females. Although it is currently native to North America and central/eastern Asia, it had a much wider distribution in the past. Populations were present across Eurasia into Western Europe during the Late Pleistocene and survived into the early Holocene in southern Sweden and the Alps; the extinct Merriam's elk subspecies ranged into Mexico. The elk has adapted well to countries where it has been introduced, including Argentina and New Zealand. Its adaptability may in fact threaten endemic species and the ecosystems into which it has been introduced. Elk are susceptible to a number of infectious diseases, some of which can be transmitted to livestock. Efforts to eliminate infectious diseases from elk populations, largely by vaccination, have had mixed success. Some cultures revere the elk as having spiritual significance. In parts of Asia, antlers and their velvet are used in traditional medicines. Elk are hunted as a game species. Their meat is leaner and higher in protein than beef or chicken.", youtube: "https://www.youtube.com/watch?v=tDJrIJcpqeo", size: "2.4 methers", classtype: "Mammal", age: "10-20", weight: 320)
        
        let animal_04 = LearningViewModel(id: UUID(), name: "Cattle", origin: "Asia", info: "Cattle are large domesticated bovines. They are most widespread species of the genus Bos. Adult females are referred to as cows and adult males are referred to as bulls.Cattle are commonly raised as livestock for meat , for milk , and for hides, which are used to make leather. They are used as riding animals and draft animals . Another product of cattle is their dung, which can be used to create manure or fuel. In some regions, such as parts of India, cattle have significant religious significance. Cattle, mostly small breeds such as the Miniature Zebu, are also kept as pets. Different types of cattle are common to different geographic areas. Taurine cattle are found primarily in Europe and temperate areas of Asia, the Americas, and Australia. Zebus are found primarily in India and tropical areas of Asia, America, and Australia. Sanga cattle are found primarily in sub-Saharan Africa. These types are further divided into over 1000 recognized breeds.", youtube: "https://www.youtube.com/watch?v=UWmbg16ywD8", size: "1.2 methers", classtype: "Mammal", age: "20", weight: 1000)
        
        let animal_05 = LearningViewModel(id: UUID(), name: "Elephant", origin: "Africa/Asia", info: "Elephants are the largest existing land animals. Three living species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. Elephantidae also contains several extinct groups, including the mammoths and straight-tusked elephants. African elephants have larger ears and concave backs, whereas Asian elephants have smaller ears, and convex or level backs. The distinctive features of all elephants include a long proboscis called a trunk, tusks, large ear flaps, massive legs, and tough but sensitive skin. The trunk is used for breathing, bringing food and water to the mouth, and grasping objects. Tusks, which are derived from the incisor teeth, serve both as weapons and as tools for moving objects and digging. The large ear flaps assist in maintaining a constant body temperature as well as in communication. The pillar-like legs carry their great weight. Elephants are scattered throughout sub-Saharan Africa, South Asia, and Southeast Asia and are found in different habitats, including savannahs, forests, deserts, and marshes. They are herbivorous, and they stay near water when it is accessible. They are considered to be keystone species, due to their impact on their environments. Elephants have a fission–fusion society, in which multiple family groups come together to socialise. Females (cows) tend to live in family groups, which can consist of one female with her calves or several related females with offspring. The groups, which do not include bulls, are usually led by the oldest cow, known as the matriarch.", youtube: "https://www.youtube.com/watch?v=Aw6GkiCvcWs", size: "2.8 methers", classtype: "Mammal", age: "56", weight: 4000)
        
        let animal_06 = LearningViewModel(id: UUID(), name: "Gorilla", origin: "Africa", info: "Gorillas are herbivorous, predominantly ground-dwelling great apes that inhabit the tropical forests of equatorial Africa. The DNA of gorillas is highly similar to that of humans, from 95 to 99% depending on what is included, and they are the next closest living relatives to humans after chimpanzees and bonobos. Gorillas are the largest living primates, reaching heights between 1.25 and 1.8 metres, weights between 100 and 270 kg, and arm spans up to 2.6 metres, depending on species and sex. They tend to live in troops, with the leader being called a silverback. The Eastern gorilla is distinguished from the Western by darker fur colour and some other minor morphological differences. Gorillas tend to live 35–40 years in the wild. The oldest gorilla ever is Fatou who is still alive at the advanced age of 65 years. Gorillas' natural habitats cover tropical or subtropical forest in Sub-Saharan Africa. Although their range covers a small percentage of Sub-Saharan Africa, gorillas cover a wide range of elevations. The mountain gorilla inhabits the Albertine Rift montane cloud forests of the Virunga Volcanoes, ranging in altitude from 2,200 to 4,300 metres. Lowland gorillas live in dense forests and lowland swamps and marshes as low as sea level, with western lowland gorillas living in Central West African countries and eastern lowland gorillas living in the Democratic Republic of the Congo near its border with Rwanda.", youtube: "https://www.youtube.com/watch?v=ieS2DsrDh18", size: "1.6 methers", classtype: "Mammal", age: "35-40", weight: 150)
        
        let animal_07 = LearningViewModel(id: UUID(), name: "Rhino", origin: "Africa", info: "A rhinoceros commonly abbreviated to rhino, is a member of any of the five extant species of odd-toed ungulates in the family Rhinocerotidae. Two of the extant species are native to Africa, and three to South and Southeast Asia. Rhinoceroses are some of the largest remaining megafauna: all weigh at least one tonne in adulthood. They have a herbivorous diet, small brains  for mammals of their size, one or two horns, and a thick, protective skin formed from layers of collagen positioned in a lattice structure. They generally eat leafy material, although their ability to ferment food in their hindgut allows them to subsist on more fibrous plant matter when necessary. Unlike other perissodactyls, the two African species of rhinoceros lack teeth at the front of their mouths; they rely instead on their lips to pluck food. Rhinoceros are killed by poachers for their horns, which are bought and sold on the black market for high prices, leading to most living rhinoceros species being considered endangered. The contemporary market for rhino horn is overwhelmingly driven by China and Vietnam, where it is bought by wealthy consumers to use in traditional Chinese medicine, among other uses.", youtube: "https://www.youtube.com/watch?v=TYklMREHD-s", size: "1.8 methers", classtype: "Mammal", age: "35-40", weight: 2000)
        
        let animal_08 = LearningViewModel(id: UUID(), name: "Skunk", origin: "Europe", info: "Skunks are mammals in the family Mephitidae. They are known for their ability to spray a liquid with a strong, unpleasant scent from their anal glands. Different species of skunk vary in appearance from black-and-white to brown, cream or ginger colored, but all have warning coloration. While related to polecats and other members of the weasel family, skunks have as their closest relatives the Old World stink badgers. Skunks are omnivorous, eating both plant and animal material and changing their diets as the seasons change. They eat insects, larvae, earthworms, grubs, rodents, lizards, salamanders, frogs, snakes, birds, moles, and eggs. They also commonly eat berries, roots, leaves, grasses, fungi and nuts.In settled areas, skunks also seek garbage left by humans. Less often, skunks may be found acting as scavengers, eating bird and rodent carcasses left by cats or other animals. Pet owners, particularly those of cats, may experience a skunk finding its way into a garage or basement where pet food is kept. Skunks commonly dig holes in lawns in search of grubs and worms.", youtube:  "https://www.youtube.com/watch?v=OKwkcOy4X2M", size: "0.4 methers", classtype: "Mammal", age: "10", weight: 3)
        
        let animal_09 = LearningViewModel(id: UUID(), name: "Turtle", origin: "Africa", info: "Turtles are an order of reptiles known as Testudines, characterized by a shell developed mainly from their ribs. There are 360 living and recently extinct species of turtles, including land-dwelling tortoises and freshwater terrapins. They are found on most continents, some islands and, in the case of sea turtles, much of the ocean. Like other reptiles, birds, and mammals, they breathe air and do not lay eggs underwater, although many species live in or around water. Genetic evidence typically places them in close relation to crocodilians and birds. Turtle shells are made mostly of bone; the upper part is the domed carapace, while the underside is the flatter plastron or belly-plate. Its outer surface is covered in scales made of keratin, the material of hair, horns, and claws. The carapace bones develop from ribs that grow sideways and develop into broad flat plates that join up to cover the body. Turtles are ectotherms or 'cold-blooded', meaning that their internal temperature varies with their direct environment. They are generally opportunistic omnivores and mainly feed on plants and animals with limited movements. Many turtles migrate short distances seasonally. Sea turtles are the only reptiles that migrate long distances to lay their eggs on a favored beach. Turtles have been hunted for their meat, for use in traditional medicine, and for their shells. Sea turtles are often killed accidentally as bycatch in fishing nets. Turtle habitats around the world are being destroyed. As a result of these pressures, many species are threatened with extinction.", youtube: "https://www.youtube.com/watch?v=xB0OodoGuUQ", size: "1.5 methers", classtype: "Reptilia", age: "10-100", weight: 300)
        
        let animal_10 = LearningViewModel(id: UUID(), name: "Shark", origin: "Ocean", info: "Sharks are a group of elasmobranch fish characterized by a cartilaginous skeleton, five to seven gill slits on the sides of the head, and pectoral fins that are not fused to the head. Modern sharks are classified within the clade Selachimorpha and are the sister group to the rays. However, the term 'shark' has also been used to refer to extinct members of the subclass Elasmobranchii, which are technically outside the Selachimorpha clade. Notable examples of improper classification include Cladoselache, Xenacanthus, and various other members of the Chondrichthyes class like the holocephalid eugenedontidans. Under this broader definition, the earliest known sharks date back to more than 420 million years ago. Acanthodians are often referred to as 'spiny sharks'; though they are not part of Chondrichthyes proper, they are a paraphyletic assemblage leading to cartilaginous fish as a whole. Since then, sharks have diversified into over 500 species. They range in size from the small dwarf lanternshark a deep sea species that is only 17 centimetres in length, to the whale shark, the largest fish in the world, which reaches approximately 12 metres in length. Sharks are found in all seas and are common to depths up to 2,000 metres. They generally do not live in freshwater, although there are a few known exceptions, such as the bull shark and the river shark, which can be found in both seawater and freshwater. Sharks have a covering of dermal denticles that protects their skin from damage and parasites in addition to improving their fluid dynamics. They have numerous sets of replaceable teeth.Several species are apex predators, which are organisms that are at the top of their food chain. Select examples include the tiger shark, blue shark, great white shark, mako shark, thresher shark, and hammerhead shark.", youtube: "https://www.youtube.com/watch?v=tfWMwG6aYzQ", size: "2.1 methers", classtype: "Chondrichthyes", age: "250-500", weight: 1500)
        learningVM.addAnimal(somebody: animal)
        learningVM.addAnimal(somebody: animal_02)
        learningVM.addAnimal(somebody: animal_03)
        learningVM.addAnimal(somebody: animal_04)
        learningVM.addAnimal(somebody: animal_05)
        learningVM.addAnimal(somebody: animal_06)
        learningVM.addAnimal(somebody: animal_07)
        learningVM.addAnimal(somebody: animal_08)
        learningVM.addAnimal(somebody: animal_09)
        learningVM.addAnimal(somebody: animal_10)
    }
}
